<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find crane_plus_description)/urdf/crane_plus_hardware.xacro"/>

  <material name="grey">
    <color rgba="0.6 0.6 0.6 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <xacro:macro name="crane_plus" params="parent servo_color bracket_color
               gripper_color *origin joints_vlimit pan_llimit pan_ulimit">
    <link name="crane_plus_base_link"/>
    <joint name="crane_plus_base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="crane_plus_base_link"/>
    </joint>

    <!-- fake gripper_link joint gives us a free servo!
         this makes us 5DOF and saves you $44.90
         that's a lot of coin! -->
    <!--<link name="gripper_link" />-->
    <!--<joint name="gripper_link_joint" type="revolute">-->
      <!--<origin xyz="0 0 .112" rpy="0 -1.57 0" />-->
      <!--<parent link="arm_wrist_flex_link"/>-->
      <!--<child link="gripper_link" />-->
      <!--<limit effort="30" velocity="1" lower="-3.14" upper="3.14"/>-->
      <!--<axis xyz="1 0 0"/>-->
    <!--</joint>-->

    <!-- Mounting plate -->
    <mounting_plate
        parent="crane_plus_base_link"
        name="crane_plus_mounting_plate"
        color="black">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </mounting_plate>

    <!-- Base bracket -->
    <bioloid_f53_fixed
        parent="crane_plus_mounting_plate_link"
        name="crane_plus_base_bracket"
        color="grey">
      <origin xyz="0 0 ${MOUNT_HEIGHT}" rpy="0 0 0"/>
    </bioloid_f53_fixed>

    <!-- Shoulder servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_base_bracket_link"
        name="crane_plus_shoulder_servo"
        color="black">
        <origin xyz="-${AX12_SIDE_SCREW_OFFSET} 0 ${AX12_BODY_MAIN_HEIGHT/2 + F53_HEIGHT}" rpy="0 0 0"/>
    </dynamixel_ax12_fixed>

    <!-- Shoulder bracket -->
    <bioloid_f2_revolute_base_axis
        parent="crane_plus_shoulder_servo_link"
        name="shoulder"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="${pan_llimit}"
        ulimit="${pan_ulimit}">
        <origin xyz="-${AX12_AXLE_OFFSET} 0 ${AX12_HORN_HEIGHT}" rpy="0 0 0"/>
    </bioloid_f2_revolute_base_axis>

    <!--Upper arm servo -->
    <dynamixel_ax12_revolute
        parent="shoulder_link"
        name="upper_arm"
        color="black"
        vlimit="${joints_vlimit}"
        llimit="${pan_llimit}"
        ulimit="${pan_ulimit}">
        <origin xyz="0 0 ${F2_AXLE_HEIGHT}" rpy="-${M_PI/2} -${M_PI/2} 0"/>
    </dynamixel_ax12_revolute>

    <!-- Upper arm upper joiner -->
    <bioloid_f3_fixed
        parent="upper_arm_link"
        name="crane_plus_upper_arm_upper_joiner"
        color="grey">
        <origin xyz="${AX12_ORIGIN_TO_AXLE+AX12_ORIGIN_TO_END_SCREW+F3_SCREW_HEIGHT} 0 0" rpy="-${M_PI/2} 0 ${M_PI/2}"/>
    </bioloid_f3_fixed>

    <!-- Upper arm lower joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_upper_arm_upper_joiner_link"
        name="crane_plus_upper_arm_lower_joiner"
        color="grey">
        <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
    </bioloid_f3_fixed>

    <!-- Lower arm servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_upper_arm_lower_joiner_link"
        name="crane_plus_lower_arm_servo"
        color="black">
      <origin xyz="0 0 ${F3_SCREW_HEIGHT+AX12_ORIGIN_TO_END_SCREW}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
    </dynamixel_ax12_fixed>

    <!-- Lower arm bracket -->
    <bioloid_f4_revolute
        parent="crane_plus_lower_arm_servo_link"
        name="lower_arm"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="${pan_llimit}"
        ulimit="${pan_ulimit}">
        <origin xyz="-${AX12_ORIGIN_TO_AXLE} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </bioloid_f4_revolute>

    <!-- Lower arm joiner -->
    <bioloid_f3_fixed
        parent="lower_arm_link"
        name="crane_plus_lower_arm_joiner"
        color="grey">
        <origin xyz="0 0 -${F4_AXLE_HEIGHT}" rpy="0 ${M_PI} 0"/>
    </bioloid_f3_fixed>

    <!-- Wrist servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_lower_arm_joiner_link"
        name="crane_plus_wrist_servo"
        color="black">
      <origin xyz="0 0 ${F3_SCREW_HEIGHT+AX12_ORIGIN_TO_END_SCREW}" rpy="0 ${M_PI/2} ${M_PI/2}"/>
    </dynamixel_ax12_fixed>

    <!-- Wrist bracket -->
    <bioloid_f2_revolute
        parent="crane_plus_wrist_servo_link"
        name="wrist"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="${pan_llimit}"
        ulimit="${pan_ulimit}">
        <origin xyz="-${AX12_ORIGIN_TO_AXLE} 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
    </bioloid_f2_revolute>

    <!-- Wrist joiner -->
    <bioloid_f3_fixed
        parent="wrist_link"
        name="crane_plus_wrist_joiner"
        color="grey">
        <origin xyz="0 0 -${F2_AXLE_HEIGHT}" rpy="0 ${M_PI} ${M_PI/2}"/>
    </bioloid_f3_fixed>

    <!-- Gripper servo -->
    <dynamixel_ax12_fixed
        parent="crane_plus_wrist_joiner_link"
        name="crane_plus_gripper_servo"
        color="black">
        <origin xyz="${AX12_SIDE_SCREW_OFFSET} 0 ${F3_SCREW_HEIGHT+AX12_ORIGIN_TO_SIDE_SCREW}" rpy="${M_PI/2} ${M_PI} 0"/>
    </dynamixel_ax12_fixed>

    <!-- Fixed finger joiner -->
    <bioloid_f3_fixed
        parent="crane_plus_gripper_servo_link"
        name="crane_plus_fixed_finger_joiner"
        color="grey">
        <origin xyz="${AX12_ORIGIN_TO_END_SCREW+F3_SCREW_HEIGHT} 0 0" rpy="-${M_PI/2} 0 ${M_PI/2}"/>
    </bioloid_f3_fixed>

    <!-- Fixed finger -->
    <fixed_finger
        parent="crane_plus_fixed_finger_joiner_link"
        name="crane_plus_fixed_finger"
        color="black">
      <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
    </fixed_finger>

    <!-- Finger bracket -->
    <bioloid_f2_revolute
        parent="crane_plus_gripper_servo_link"
        name="gripper"
        color="grey"
        vlimit="${joints_vlimit}"
        llimit="${pan_llimit}"
        ulimit="${pan_ulimit}">
        <origin xyz="-${AX12_ORIGIN_TO_AXLE} 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
    </bioloid_f2_revolute>

    <!-- Movin finger -->
    <moving_finger
        parent="gripper_link"
        name="crane_plus_moving_finger"
        color="black">
      <origin xyz="0 0 -${F2_AXLE_HEIGHT}" rpy="${M_PI} 0 0"/>
    </moving_finger>

  </xacro:macro>
</robot>
