<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="SCALE_MM" value="0.001"/>
  <xacro:property name="SCALE_CM" value="0.01"/>

  <xacro:property name="AX12_WIDTH" value="0.032"/>
  <xacro:property name="AX12_LENGTH" value="0.050"/>
  <!-- This height is measured from the bottom axel mount to the top of the
       servo horn (the round bit on the axel).-->
  <xacro:property name="AX12_HEIGHT" value="0.040"/>
  <!-- This height is measured from the screw brackets on the base to the top
       of the servo horn.-->
  <xacro:property name="AX12_MOUNTED_HEIGHT" value="0.037"/>
  <!-- This height is measured from the bottom axel mount to the top of the
       servo, excluding the horn.-->
  <xacro:property name="AX12_BODY_HEIGHT" value="0.038"/>
  <!-- The distance from the centreline of the servo to the centre of the
       axel.-->
  <xacro:property name="AX12_AXEL_OFFSET" value="0.0135"/>

  <xacro:property name="F2_HEIGHT" value="0.0265"/>
  <xacro:property name="F3_HEIGHT" value="0.009"/>
  <xacro:property name="F4_HEIGHT" value="0.0525"/>
  <!-- This height goes to where the servo contacts the screw points. It does
       not include the nubs on top that fit between the servo screw attachment
       points.-->
  <xacro:property name="F53_HEIGHT" value="0.004"/>

  <xacro:property name="MOUNT_HEIGHT" value="0.001"/>

  <xacro:macro name="mounting_plate" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>

      <visual>
        <origin xyz="-0.025 -0.025 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://crane_plus_description/meshes/mount.stl" scale="1 1 1"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="-0.025 -0.025 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.001"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="bioloid_f53_fixed" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://crane_plus_description/meshes/f53.stl" scale="${SCALE_CM} ${SCALE_CM} ${SCALE_CM}"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="-${M_PI/2} 0 0"/>
        <geometry>
          <box size="0.022 0.032 0.007"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="dynamixel_ax12_fixed" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>

      <visual>
        <origin xyz="-0.0028 0 ${AX12_BODY_HEIGHT/2}" rpy="-${M_PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://crane_plus_description/meshes/ax12_box.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="-0.0028 0 ${AX12_BODY_HEIGHT/2}" rpy="-${M_PI/2} 0 0"/>
        <geometry>
          <box size="${AX12_LENGTH} ${AX12_WIDTH} ${AX12_BODY_HEIGHT}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="bioloid_f2_revolute" params="parent name color llimit ulimit vlimit *origin">
    <joint name="${name}_joint" type="revolute">
      <insert_block name="origin"/>
      <axis xyz="0 0 1"/>
      <limit effort="30" velocity="${vlimit}" lower="${llimit}" upper="${ulimit}"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0.0265" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://crane_plus_description/meshes/f2.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="0 0 0.0265" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <box size="0.025 0.0485 0.0375"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

</robot>
