controller_manager_ns: /
controller_list:
  - name: crane_plus_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_joint
      - upper_arm_joint
      - lower_arm_joint
      - wrist_joint
