controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_joint
      - upper_arm_joint
      - lower_arm_joint
      - wrist_joint
  - name: fake_gripper_controller
    joints:
      - gripper_joint