arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      crane_plus_shoulder_bracket_rev_joint
      crane_plus_upper_arm_servo_joint
      crane_plus_lower_arm_bracket_joint
      crane_plus_wrist_bracket_joint
